### ISSUE TITLE
evaluation datasets/corpora/cases?

### ISSUE THREAD

**Issue by VladimirAlexiev** [reconciliation-api/charter#1]
The charter says "Writing test suites, validators for such protocols".
Do we also want to address evaluation resources, such as datasets, corpora and cases?

I would say NO since this is a complex and effort-intensive task, and it's the domain of OEAI and similar evaluation initiatives.

**Comment by wetneb** [comment]
Makes sense. Any dataset is likely to be specific to a particular domain or data provider and the purpose is to be as broad as possible.

What is the OEAI though?

**Comment by VladimirAlexiev** [comment]
I mean the http://oaei.ontologymatching.org/ series of competitions/workshops. Despite the name, it has more to do with evaluation of **entity** matching

We have a VIAF recon server and some evaluation scenarios and resources.

**Comment by wetneb** [comment]
Nice, thanks!
